### ISSUE TITLE
PTRView content pushed up with each refresh

### ISSUE THREAD

**Issue by fhadsheikh** [moschan/react-native-pull-to-refresh#15]
Every time PTRView is pulled down, the content is pushed up.

<img width="375" alt="screen shot 2017-06-26 at 10 29 53 am" src="https://user-images.githubusercontent.com/22453066/27544200-68e5f776-5a5a-11e7-8899-d3244eab2d9e.png">

**Comment by harshazaz** [comment]
In iOS device every time PTRView is pulled down, the content is pushed up. Does anyone know a fix ?

**Comment by thinhvo-groove** [comment]
@fhadsheikh Can you please tell me how you fix this issue? I have the same problem with this library
