### ISSUE TITLE
Content can be pushed up but doesn't come back down

### ISSUE THREAD

**Issue by fhadsheikh** [moschan/react-native-pull-to-refresh#18]
You can push content up inside PTRView, but it doesn't come back down. I think this is because the content can be pushed to where the arrow icon sits.

![screen shot 2017-08-24 at 5 14 09 pm](https://user-images.githubusercontent.com/22453066/29689028-bba38906-88ef-11e7-9fc8-23c57d70e381.png)

**Comment by nikhilsaraf** [comment]
@fhad-getmaple I don't see this issue when using the component. Can you share a code sample of how you are using the component?
