### ISSUE TITLE
Every second refresh different arrow offset

### ISSUE THREAD

**Issue by mauron85** [moschan/react-native-pull-to-refresh#2]
Hi, first I must say this is great plugin. 

It is intended that every second refresh attempt, arrow is shifted down bit (with animation). And next refresh it stay's on the top?

![react-native-pull-to-refresh](https://cloud.githubusercontent.com/assets/359450/12468836/47d64310-bfe7-11e5-8e19-c34e0795fd5d.png)

**Comment by moschan** [comment]
Thank you for your interest!

did you set up a code like this ?
https://github.com/moschan/react-native-pull-to-refresh/blob/master/example/index.ios.js

And could you tell me the version which you used?

if you can show the source code that problem happened, Maybe I will fix a problem or this library quickly.

**Comment by mauron85** [comment]
Not exactly. I customised it bit, as by default there was huge empty space. I've made Movie demo, which replicates my issue on iOS. And it seems not working on android at all.

https://github.com/mauron85/PullRefreshMoviesReactNative

**Comment by moschan** [comment]
Thanks a lot.

I will check and i respond to you in a few days.

**Comment by moschan** [comment]
I detected bug and I updated this component.

I sent you a pull request that is contained fixed source code and demo gif.
https://github.com/mauron85/PullRefreshMoviesReactNative/pull/1

Please check it! :smile_cat:

**Comment by moschan** [comment]
This component still not adapt to Android.
But I will fix the component for adapt to Android soon.

**Comment by mauron85** [comment]
Great work. Now it's perfect. Thank you.

BTW. I didn't get the idea about the delay prop. Do you try to keep loading animation running for configurable amount of seconds defined by delay prop? If so, one remark, ajax request are unpredictable, so they can be running longer (or) shorter than delay prop. seconds.

**Comment by moschan** [comment]
Thank you for your question.

Yes, ajax request is unpredictable. The reason why derey option is exist is for UX. If  the time of ajax request is too short, maybe user cannot perceive thing that loading is finished.

Of course, short loading time is better. But you can set minimum delay time using `delay` props.
Let's think about when you set `delay={1000}`.
If ajax request time is shorter than 1000 ms, animation least continue to 1000 ms. but if ajax request time is longer than 1000 ms, animation is finished immediately when request is finished.

Of course, you can choose that whether you should set delay props or not.

Thank you:smiley_cat:

**Comment by moschan** [comment]
@mauron85 
If you still have any problem about this topic, you can reopen this issue. :+1:
