### ISSUE TITLE
SyntaxError on loading `arrow.png` image

### ISSUE THREAD

**Issue by mayask** [moschan/react-native-pull-to-refresh#7]
When I import your component, I get this error.

react-native version 0.24.1

![simulator screen shot apr 20 2016 11 43 59 am](https://cloud.githubusercontent.com/assets/958221/14668492/477ddbba-06ed-11e6-96cf-a4eb5c53bd8e.png)

The issue is in `Indicator.js`.

<img width="815" alt="screen shot 2016-04-20 at 11 45 40 am" src="https://cloud.githubusercontent.com/assets/958221/14668527/77548b7c-06ed-11e6-8825-c78cba0a8d50.png">

**Comment by moschan** [comment]
Thank you for your report.

I will check soon!:smile_cat:

**Comment by mayask** [comment]
@moschan This error has gone once I removed `node_modules` folder and ran `npm i` command.

**Comment by moschan** [comment]
@myaskevich 
Thank you for your report.

If you have any problem or question, you can open issue without hesitation:smile_cat:

thx.
