### ISSUE TITLE
Apply .ios .android naming

### ISSUE THREAD

**Issue by mschipperheyn** [moschan/react-native-pull-to-refresh#8]
I'm not sure you are aware of this but RN currently supports dynamic switching between ios and android specific components by a file naming convention

myComponent.ios.js
myComponent.android.js

import MyComponent from 'myComponent';//import ios version on iOS and android on Android

**Comment by moschan** [comment]
Thank you for your issue!

Oh, I didn't know that:open_mouth:

Does this link shows correct things about what you have mentioned?
https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions

**Comment by mschipperheyn** [comment]
yup

**Comment by moschan** [comment]
I see.

I will update this component  based on that.

**Comment by moschan** [comment]
This is fixed. thanks.
